version: '3.8'

services:
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        ports:
            - '4306:3306'
        volumes:
            - ./docker/data/mysql:/var/lib/mysql

    php:
        container_name: notionism-php
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - '9000:9000'
        volumes:
            - .:/var/www/
        depends_on:
            - mysql

    nginx:
        container_name: notionism-nginx
        image: nginx:stable-alpine
        ports:
            - '8000:80'
        volumes:
            - .:/var/www/
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
